# Generated by Django 2.1.3 on 2018-11-15 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20181114_2145'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='album',
            unique_together={('user', 'title')},
        ),
    ]
